WORK-NECTOR/OFFIZZ-FE

- src/app/information/components/MainCharacterBox/MainCharacterBox.styled.ts
- src/app/information/components/MainCharacterBox/MainCharacterBox.tsx
- src/app/information/components/MainCharacterBox/index.tsx
- src/app/information/components/Recommend/Recommend.styled.ts
- src/app/information/components/Recommend/Recommend.tsx
- src/app/information/components/Recommend/index.tsx
- src/app/information/page.module.css
- src/app/information/page.tsx
- src/app/information/quration/components/Category/Category.styled.ts
- src/app/information/quration/components/Category/Category.tsx
- src/app/information/quration/components/Category/index.tsx
- src/app/information/quration/components/MainMsg/MainMsg.styled.ts
- src/app/information/quration/components/MainMsg/MainMsg.tsx
- src/app/information/quration/page.module.css
- src/app/information/quration/page.tsx
> OFZ-37 chore: config 설정

- src/components/LocationItem/LocationItem.stories.ts
LocationItem props 때문에 오류나는 거 핫픽스 합니다!
> OFZ-43 fix: LocationItem story 오류 해결

- src/components/RecapBox/RecapBox.stories.ts
> OFZ-43 fix: RecapBox story 오류 해결

- src/components/LocationItem/LocationItem.stories.ts
- src/components/RecapBox/RecapBox.stories.ts
> develop 변경사항 main에 반영

- src/components/TimeRange/TimeRange.stories.ts
> OFZ-43 fix: TimeRange story 오류 해결

- src/components/RecapBox/RecapBox.stories.ts
- src/components/TimeRange/TimeRange.stories.ts
> develop 변경 사항 main에 반영

- src/app/information/components/MainCharacterBox/MainCharacterBox.styled.ts
- src/app/information/components/MainCharacterBox/MainCharacterBox.tsx
- src/app/information/components/MainCharacterBox/index.tsx
- src/app/information/components/Recommend/Recommend.styled.ts
- src/app/information/components/Recommend/Recommend.tsx
- src/app/information/components/Recommend/index.tsx
- src/app/information/page.module.css
- src/app/information/page.tsx
- src/app/information/quration/components/Category/Category.styled.ts
- src/app/information/quration/components/Category/Category.tsx
- src/app/information/quration/components/Category/index.tsx
- src/app/information/quration/components/MainMsg/MainMsg.styled.ts
- src/app/information/quration/components/MainMsg/MainMsg.tsx
- src/app/information/quration/page.module.css
- src/app/information/quration/page.tsx
This reverts commit 66e8b78a659a69862464f7641e97e0031da860a5.
> Revert "delete"

- src/components/PaginationBar/PaginationBar.styled.ts
- src/components/PaginationBar/PaginationBar.tsx
- src/types/pagination.type.ts
> OFZ-48 fix: PaginationBar 오류 해결

- .eslintrc.json
- src/app/focus/page.tsx
- src/app/information/components/Recommend/Recommend.tsx
- src/app/information/components/Todo/Todo.tsx
- src/app/information/page.tsx
- src/components/Modal/Modal.tsx
- src/components/Tab/Tab.tsx
- src/services/office/useRecRegionOfficeQuery.ts
> OFZ-48 fix: ESLint 오류 해결

- src/app/focus/page.tsx
- src/app/information/page.tsx
- src/store/useSelectTime.ts
- src/store/useSelectTodo.ts
> OFZ-48 fix: import create 오류 및 useSearchParams 로직 수정

- src/app/focus/page.tsx
- src/app/information/page.tsx
> OFZ-48 fix: Hook 오류 해결

- src/app/focus/components/FocusSearchParams/FocusSearchParams.tsx
- src/app/focus/page.tsx
- src/app/information/components/InfoSearchParams/InfoSearchParams.tsx
- src/app/information/page.tsx
> OFZ-48 fix: SearchParams 컴포넌트 분리

- src/app/focus/page.tsx
- src/app/information/page.tsx
> OFZ-48 fix: Suspense 추가

- src/api/office/getOfficeDetail.ts
- src/api/office/searchOffice.ts
- src/app/recommend/page.module.css
- src/app/recommend/page.tsx
- src/components/OfficeAccordion/OfficeAccordion.tsx
- src/components/PaginationBar/PaginationBar.tsx
- src/constants/office.ts
- src/services/office/useOfficeDetailQuery.ts
- src/services/office/useSearchOfficeQuery.ts
추천 페이지 완성
- 추천 페이지 UI 완성
- 지역별 오피스 + 검색 오피스 데이터 api 연결 완료
- 페이지네이션 구현 완료
- OfficeAccordion 상세 api 연결
- search 쿼리 size랑 page 유동적으로 받을 수 있게 구현함 (optional하게 안 하는 게 좋을 것 같긴 한데 쓰고 있는 곳이 있을 것 같아서 일단 optional 하게 하고 디폴트값 지정함)
- 검색바 디테일은 구현X (우선순위가 낮다고 생각해서 검색 기능 자체만 구현했습니다)
- map 돌릴 때 idx 를 key로 쓰지 말라는 lint 오류가 몇개 났는데 key로 대체할 수 있는 다른 인덱스값이 없어서 오류 무시 처리햇습니당
> OFZ-50 feat: 추천 페이지 완성

- src/components/LocationItem/LocationItem.stories.ts
> OFZ-52 fix: LocationItem story 오류 해결

- src/app/information/components/Todo/Todo.tsx
> OFZ-51 fix: 배포 오류 : 아이콘 이미지 수정

- src/app/information/components/Todo/Todo.tsx
> hotFix : StaticImageData 추가

- src/app/information/components/Todo/Todo.tsx
> hotfix: Image태그 추가

- src/app/information/quration/page.tsx
> hotfix: useSearchOfficesQuery의 filter 수정

- src/api/office/searchWorkOffice.ts
- src/app/recommend/page.tsx
- src/services/office/useSearchWorkOfficeQuery.ts
- 제가 쓰던 searchOffice 쿼리를, searchWorkOffice 쿼리라는 별도의 쿼리 파일로 만들어서 따로 연결했습니다!
- 검색 잘 동작하는지 확인했습니다~
> OFZ-56 fix: searchOffice -> searchWorkOffice 쿼리 수정

- .eslintrc.json
- src/app/login/page.module.css
- src/app/login/page.tsx
- src/app/signup/page.module.css
- src/app/signup/page.tsx
> OFZ-58 fix: 자체 로그인 & 회원가입 로직 작업

- src/app/login/page.tsx
- src/app/signup/page.tsx
- src/components/Header/Header.tsx
카카오 디벨로퍼스 플랫폼에 도메인 추가
로그인 submit 오류 해결
> OFZ-58 fix: 카카오 관련 오류 해결

- src/app/information/components/Recommend/Recommend.styled.ts
- src/app/information/components/Record/Record.tsx
- src/app/information/quration/page.tsx
- src/app/recap/page.tsx
- src/components/InFoBox/InFoBox.tsx
- src/components/KakaoMap/KakaoMap.tsx
- src/components/RecapBox/RecapBox.styled.ts
- src/components/RecapBox/RecapBox.tsx
- src/types/recap.type.ts
리캡 api 연결
리캡 api 연결
- 실 데이터가 없어서 스웨거 보고 샘플 데이터로 넣어놨습니다 !
- api연결 잘 되는건 확인해서 실 데이터 들어가지면 샘플데이터 삭제하겠습니다 !( 지금은 혜원님 작업 이어하시기 쉽게 넣어놨습니다)
> OFZ-57 feat: 리캡 api 연결

- src/components/RecapBox/RecapBox.stories.ts
> OFZ-59 fix: RecapBox story 오류 해결

- src/app/recap/detail/components/BackNextBtn/BackNextBtn.tsx
- src/app/recap/detail/components/RecapWorkTime/RecapWorkTime.tsx
- src/app/recap/page.tsx
> OFZ-53 fix: 배포 오류 해결

- src/api/workation/getOngoing.ts
- src/app/page.tsx
- src/services/workation/useOngoingWorkation.ts
- 현재 진행 중인 워케이션 유무에 따라 라우팅
- 현재 진행 중인 워케이션이 없으면 `/` 유지
- 현재 진행 중인 워케이션이 있으면 `/information` 진입
UI 변화는 딱히 없습니다!
> OFZ-61 feat: 현재 진행 중인 워케이션이 있으면 /information 진입
